"""Add token blacklist table

Revision ID: c92428c04220
Revises: af6c7c4054db
Create Date: 2026-02-10 17:27:43.855323

"""
from collections.abc import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c92428c04220'
down_revision: Union[str, None] = 'af6c7c4054db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    # ### end Alembic commands ###
